project:
  type: book
  output-dir: docs

book:
  title: "Statistical Inference via Data Science"
  subtitle: "A ModernDive into R and the Tidyverse (Second Edition)"
  author:
    - name: Chester Ismay
    - name: Albert Y. Kim
    - name: Arturo Valdivia
  date: last-modified
  date-format: "MMMM D, YYYY"
  repo-url: https://github.com/moderndive/ModernDive_book/
  repo-branch: v2
  repo-actions: [edit]
  
  chapters:
    - index.qmd
    - 00-foreword.qmd
    - 00-preface.qmd
    - 01-getting-started.qmd
    - 02-visualization.qmd
    - 03-wrangling.qmd
    - 04-tidy.qmd
    - 05-regression.qmd
    - 06-multiple-regression.qmd
    - 07-sampling.qmd
    - 08-confidence-intervals.qmd
    - 09-hypothesis-testing.qmd
    - 10-inference-for-regression.qmd
    - 11-tell-your-story-with-data.qmd
    - part: "Appendices"
      chapters:
        - 91-appendixA.qmd
        - 92-appendixB.qmd
        - 93-appendixC.qmd
        - 94-appendixD.qmd
        - 95-appendixE.qmd
    - 99-references.qmd
  
  navbar:
    left:
      - text: "Home"
        href: index.html
    right:
      - icon: github
        href: https://github.com/moderndive/ModernDive_book/tree/v2/

  page-footer:
    left: |
      This work by Chester Ismay, Albert Y. Kim, and Arturo Valdivia is licensed under 
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
    right: |
      <a href="https://www.netlify.com">
        <img src="https://www.netlify.com/v3/img/components/netlify-color-accent.svg" alt="Deploys by Netlify" />
      </a>

bibliography: 
  - bib/books.bib
  - bib/packages.bib
  - bib/articles.bib

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    code-link: true
    highlight-style: pygments
    fig-align: center
    fig-width: 6
    fig-asp: 0.667
    link-citations: true
    include-in-header: _includes/analytics.html
    include-before-body: _includes/logo.html
    filters:
      - _extensions/bookdown-blocks.lua
    
execute:
  freeze: auto
  warning: false

crossref:
  chapters: true
  fig-prefix: "FIGURE"
  tbl-prefix: "TABLE"

knitr:
  opts_knit:
    root.dir: null
  opts_chunk:
    echo: true
    eval: true
    warning: false
    message: true
    comment: ""
    fig.align: center
    R.options:
      width: 120
