project:
  type: book
  output-dir: docs

book:
  title: "Statistical Inference via Data Science"
  subtitle: "A ModernDive into R and the Tidyverse (Second Edition)"
  author: 
    - name: "Chester Ismay"
    - name: "Albert Y. Kim" 
    - name: "Arturo Valdivia"
  date: today
  date-format: "MMMM D, YYYY"
  repo-url: https://github.com/moderndive/ModernDive_book/
  repo-branch: v2
  repo-actions: [edit]
  chapters:
    - index.qmd
    - 00-foreword.qmd
    - 00-preface.qmd
    - part: "Getting Started"
      chapters:
        - 01-getting-started.qmd
    - part: "Data Science with tidyverse"
      chapters:
        - 02-visualization.qmd
        - 03-wrangling.qmd
        - 04-tidy.qmd
    - part: "Statistical Modeling with moderndive"
      chapters:
        - 05-regression.qmd
        - 06-multiple-regression.qmd
    - part: "Statistical Inference with infer"
      chapters:
        - 07-sampling.qmd
        - 08-confidence-intervals.qmd
        - 09-hypothesis-testing.qmd
        - 10-inference-for-regression.qmd
    - part: "Conclusion"
      chapters:
        - 11-tell-your-story-with-data.qmd
    - part: "Appendices"
      chapters:
        - 91-appendixA.qmd
        - 92-appendixB.qmd
        - 93-appendixC.qmd
        - 94-appendixD.qmd
        - 95-appendixE.qmd
    - 99-references.qmd
  navbar:
    left:
      - text: "Home"
        href: index.html
    right:
      - icon: github
        href: https://github.com/moderndive/ModernDive_book/tree/v2/
  page-footer:
    left: |
      This work by [Chester Ismay](https://chester.rbind.io/), [Albert Y. Kim](https://rudeboybert.rbind.io/), and [Arturo Valdivia](https://avaldivi6.github.io) is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
    right: |
      <a href="https://www.netlify.com"><img src="https://www.netlify.com/v3/img/components/netlify-color-accent.svg" alt="Deploys by Netlify" /></a>

bibliography: 
  - bib/books.bib
  - bib/packages.bib
  - bib/articles.bib

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    toc-depth: 3
    number-sections: true
    link-citations: true
    include-in-header:
      - _includes/analytics.html
    include-before-body:
      - _includes/logo.html
    code-link: true
    code-fold: false
    code-tools: false
    fig-width: 6
    fig-asp: 0.667

knitr:
  opts_chunk:
    echo: true
    warning: false
    message: true
    comment: NA
    fig.align: center
    fig.retina: 1
    out.width: "100%"
